formatter: "markdown table"

output:
  file: tfdocs.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: false
  color: false
  default: false
  description: false
  escape: true
  hide-empty: true
  html: false
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true